footprint: [[0.15,0.25],[-0.55,0.25],[-0.55,-0.25],[0.15,-0.25]]
footprint_padding: 0.04
inflation_layer:
  inflation_radius: 0.5 # 2xfootprint, it helps to keep the global planned path farther from obstacles
transform_tolerance: 2
recovery_behavior_enabled: false

obstacle_layer:
  obstacle_range: 4.5
  raytrace_range: 5
  max_obstacle_height: 2.0
  # min_obstacle_height: -2.0
  track_unknown_space: true

  # observation_sources: laser_scan_sensor point_cloud_sensorA point_cloud_sensorB
  observation_sources: point_cloud_sensorA point_cloud_sensorB

  laser_scan_sensor: {
    data_type: LaserScan,
    topic: scan,
    expected_update_rate: 0.025,
    marking: true,
    clearing: true
  }

  point_cloud_sensorA: {
    sensor_frame: base_footprint,
    data_type: PointCloud2,
    topic: obstacles_cloud,
    expected_update_rate: 0.5,
    marking: true,
    clearing: true,
    min_obstacle_height: -2.0
  }

  point_cloud_sensorB: {
    sensor_frame: base_footprint,
    data_type: PointCloud2,
    topic: ground_cloud,
    expected_update_rate: 0.5,
    marking: false,
    clearing: true,
    min_obstacle_height: -2.0 # make sure the ground is not filtered
  }


